### PR TITLE
Fixed and Improved Platform.as 31/05/2017

### PR DESCRIPTION
**Pull request by Snky**
Added isFullscreen()
Fixed/Improved isLandscape()
Changed all uses of .fullscreenWidth to .stageWidth;
Changed all uses of .fullscreenHeight to .stageHeight;

Now accommodates for all three possible orientations: portrait, landscape, width==height(any?)
Now accommodates for all three possible stage.displayState(s)

### CODE REVIEW

**Comment by SnkyGames** [comment]
>< ..shows all my commits, I'm not used to this guys, sorry, I tried my best to manually tab each line in GitHub, I found a spacing error every commit on my fork, so the change history will probably look like a cluster ****. =/

**Comment by gsynuh** [comment]
@Snky If I merge this, what do you think about this whole thing being renamed something like ApplicationPlatform or something , it seems a bit more explicit and seperate from platform objects, what do you think?

**Comment by alamboley** [comment]
Just saw Starling have some nice methods https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/utils/SystemUtil.as

**Comment by Snky** [comment]
Hey guys, I missed the notifications for your replies (sorry for the late reply), I don't mind how you guys want to go about it, use the class as you please, I'm going to continue working on Platform.as and Platform.hx for myself, so if you think a different name is better, or a merge, go ahead! 

If you want to still receive new pull requests, I can do that (and do the renaming on your behalf to suit CE).
If you want to go about providing this feature for your developers differently, I don't mind that either. 

Regarding merging, I think there is a closed issue perhaps, that me and Aymeric discussed and thought Platform was a better name than Mobile, as it contains information related to browsers and desktop platforms, not just phone devices. 

Found the reference to the class name choice: #226

**Comment by Snky** [comment]
> Added isFullscreen()
Fixed/Improved isLandscape()
Changed all uses of .fullscreenWidth to .stageWidth;
Changed all uses of .fullscreenHeight to .stageHeight;

> Now accommodates for all three possible orientations: portrait, landscape, width==height(any?)
Now accommodates for all three possible stage.displayState(s)

On top of these changes that were not pushed in July 2016, I have:

+Added a check for OpenFL as a runner (more of an addition to my Haxe Platform.hx)
+Added a check for Blackberry
+Added isMobile()
+Merged iPhoneFive with iPhoneSE -> function name: isIphoneFiveSE()
+Merged iPhoneSix with iPhoneSeven -> function name: isIphoneSixSeven()
+Merged iPhoneSixPlus with iPhoneSevenPlus -> function name: isIphoneSixSevenPlus()
(These devices share the same resolution, so for now they will share a function)

Code refactor / format as you please, and rename the class to whatever suits your community.

**Comment by Snky** [comment]
> Added isFullscreen()
Fixed/Improved isLandscape()
Changed all uses of .fullscreenWidth to .stageWidth;
Changed all uses of .fullscreenHeight to .stageHeight;

> Now accommodates for all three possible orientations: portrait, landscape, width==height(any?)
Now accommodates for all three possible stage.displayState(s)

On top of these changes that were not pushed to CE in July 2016, I have:

+Added a check for OpenFL as a runner (more of an addition to my Haxe Platform.hx)
+Added a check for Blackberry
+Added isMobile()
+Merged iPhoneFive with iPhoneSE -> function name: isIphoneFiveSE()
+Merged iPhoneSix with iPhoneSeven -> function name: isIphoneSixSeven()
+Merged iPhoneSixPlus with iPhoneSevenPlus -> function name: isIphoneSixSevenPlus()
(These devices share the same resolution, so for now they will share the same functions)

Code refactor / format as you please, and rename the class to whatever suits your community.
(31/05/2017 commit ref: https://github.com/DaVikingCode/Citrus-Engine/pull/284/commits/35846361e2d7adaaa75b68db75f1154c3c7fe037)

**Comment by seanmonster** [comment]
Hey, sorry to hijack this thread. Trying to get ahold of @Snky please ping me back, thanks.

**Pull request closed without merging**
