### PR TITLE
Update Platform.as

### PR DESCRIPTION
**Pull request by SnkyGames**
Uhhh, did I make this pull request properly? :dango:

### CODE REVIEW

**Comment by alamboley** [comment]
Well, there are so many format changes that in fact I don't know what really has changed ?

**Comment by SnkyGames** [comment]
Yes, I don't remember reformatting the entire file, but also in the. CE issues list ( recently updated ) I mentioned the changes which was a fix for iPhone 4 / 5 detection and also a new additional query for the iPad pro. Apologies for the unclear changes.

**Comment by gsynuh** [comment]
This happens if we don't use the same editors its ok.

I'll put the reference to the issue is that it? 
https://github.com/DaVikingCode/Citrus-Engine/issues/226

**Comment by SnkyGames** [comment]
Yes that's the correct issue, I'm using FlashDevelop 5.1.0

**Pull request closed without merging**
